// FR lang variables - Sarki pour Joomla! FR 2011-07-17
tinyMCE.addI18n('fr.table_dlg',{
general_tab:"G\u00E9n\u00E9ral",
advanced_tab:"Avanc\u00E9",
general_props:"Propri\u00E9t\u00E9s g\u00E9n\u00E9rales",
advanced_props:"Propri\u00E9t\u00E9s avanc\u00E9es",
rowtype:"Ligne du tableau",
title:"Ins\u00E9rer/Modifer un tableau",
width:"Largeur",
height:"Hauteur",
cols:"Colonnes",
rows:"Lignes",
cellspacing:"Marge ext\u00E9rieure",
cellpadding:"Marge int\u00E9rieure",
border:"Bordure",
align:"Alignement horizontal",
align_default:"D\u00E9faut",
align_left:"Gauche",
align_right:"Droite",
align_middle:"Centr\u00E9",
row_title:"Propri\u00E9t\u00E9s de ligne",
cell_title:"Propri\u00E9t\u00E9s de cellule",
cell_type:"Type",
valign:"Alignement vertical",
align_top:"Haut",
align_bottom:"Bas",
bordercolor:"Couleur de bordure",
bgcolor:"Couleur de fond",
merge_cells_title:"Fusionner les cellules",
id:"Id du tableau",
style:"Styles",
langdir:"Direction d'\u00E9criture",
langcode:"Code langue",
mime:"Target MIME type",
ltr:"Gauche \u00E0 droite",
rtl:"Droite \u00E0 gauche",
bgimage:"Image de fond",
summary:"Sommaire",
td:"Donn\u00E9es",
th:"En-t\u00EAtes",
cell_cell:"Modifier la cellule active",
cell_row:"Modifier toutes les cellules de la ligne",
cell_col:"Modifier toutes les cellules de la colonne",
cell_all:"Modifier toutes les cellules du tableau",
row_row:"Modifier la ligne active",
row_odd:"Modifier toutes les lignes impaires",
row_even:"Modifier toutes les lignes paires",
row_all:"Modifier toutes les lignes du tableau",
thead:"En-t\u00EAte",
tbody:"Contenu",
tfoot:"Pied",
scope:"Affecter",
rowgroup:"Lignes",
colgroup:"Colonnes",
col_limit:"Vous avez d\u00E9pass\u00E9 le nombre maximum des colonnes de {$cols}.",
row_limit:"Vous avez d\u00E9pass\u00E9 le nombre maximum des lignes de {$rows}.",
cell_limit:"Vous avez d\u00E9pass\u00E9 le nombre maximum des cellules de {$cells}.",
missing_scope:"Vous devez affecter l'en-t\u00EAte \u00E0 un \u00E9l\u00E9ment du tableau.",
caption:"L\u00E9gende",
frame:"S\u00E9paration",
frame_none:"Aucun",
frame_groups:"Groupes",
frame_rows:"Lignes",
frame_cols:"Colonnes",
frame_all:"Tous",
rules:"Cadres",
rules_void:"Int\u00E9rieur",
rules_above:"Int\u00E9rieur + Lignes dessus",
rules_below:"Colonnes et Lignes",
rules_hsides:"Int\u00E9rieur + Bord haut",
rules_lhs:"Int\u00E9rieur + Bord gauche",
rules_rhs:"Int\u00E9rieur + Bord droite",
rules_vsides:"Int\u00E9rieur + Bord bas",
rules_box:"Int\u00E9rieur + Cadre",
rules_border:"Int\u00E9rieur + Bords"
});