// FR lang variables - Sarki pour Joomla! FR 2011-07-17
tinyMCE.addI18n('fr.media_dlg',{
title:"Ins\u00E9rer/Editer un m\u00E9dia",
general:"G\u00E9n\u00E9ral",
advanced:"Avanc\u00E9",
file:"Fichier",
list:"Liste",
size:"Taille",
preview:"Pr\u00E9visualisation",
constrain_proportions:"Proportionnel",
type:"Type",
id:"Id du m\u00E9dia",
name:"Nom",
class_name:"Classes CSS",
vspace:"Espace vertical",
hspace:"Espace horizontal",
play:"Lecture auto",
loop:"Boucle",
menu:"Menu",
quality:"Qualit\u00E9",
scale:"Affichage",
align:"Alignement",
salign:"SAlignement",
wmode:"Fond",
bgcolor:"Fond couleur",
base:"Base",
flashvars:"Variables Flash",
liveconnect:"SW Connection directe",
autohref:"URL Automatique",
cache:"Cache",
hidden:"Masqu\u00E9",
controller:"Contr\u00F4leur",
kioskmode:"Mode Kiosk pour IE",
playeveryframe:"Afficher toutes les images",
targetcache:"Cache cibl\u00E9",
correction:"Aucune correction",
enablejavascript:"Activer JavaScript",
starttime:"Image de d\u00E9part",
endtime:"Image de fin",
href:"Adresse URL",
qtsrcchokespeed:"Vitesse Choke",
target:"Cible",
volume:"Volume",
autostart:"Lecture automatique",
enabled:"Activ\u00E9",
fullscreen:"Pleine page",
invokeurls:"Appeler URLs",
mute:"Muet",
stretchtofit:"Adaptation \u00E0 la taille",
windowlessvideo:"Vid\u00E9o sans cadre",
balance:"Balance",
baseurl:"URL de Base",
captioningid:"Id L\u00E9gende",
currentmarker:"Marqueur actuel",
currentposition:"Position actuelle",
defaultframe:"Taille par d\u00E9faut",
playcount:"Compteur",
rate:"Vitesse",
uimode:"UI Mode",
flash_options:"Options Flash",
qt_options:"Options Quicktime",
wmp_options:"Options Windows media player",
rmp_options:"Options Real media player",
shockwave_options:"Options Shockwave",
autogotourl:"Atteindre URL automatiquement",
center:"Centr\u00E9",
imagestatus:"Statut Image",
maintainaspect:"Proportionnel",
nojava:"Java desactiv\u00E9",
prefetch:"Activer Prefetch",
shuffle:"Mode al\u00E9atoire",
console:"Activer Console",
numloop:"Nombre de boucle",
controls:"Contr\u00F4les",
scriptcallbacks:"Script callbacks",
swstretchstyle:"Remplissage",
swstretchhalign:"Horizontale",
swstretchvalign:"Verticale",
sound:"Son",
progress:"Progression",
qtsrc:"Source Quicktime",
qt_stream_warn:"Vous devez ajouter le source du streaming rtsp dans le champ Source Quicktime de l'onglet avanc\u00E9.\nVous devriez ajouter \u00E9galement une version sans streaming",
align_top:"Haut",
align_right:"Droite",
align_bottom:"Bas",
align_left:"Gauche",
align_center:"Centr\u00E9",
align_top_left:"Haut Gauche",
align_top_right:"Haut Droite",
align_bottom_left:"Bas Gauche",
align_bottom_right:"Bas Droite",
flv_options:"Options vid\u00E9o Flash",
flv_scalemode:"Mode affichage",
flv_buffer:"Tampon",
flv_starttime:"Point de d\u00E9part",
flv_defaultvolume:"Volume par d\u00E9faut",
flv_hiddengui:"Masquer GUI (Graphical User Interface)",
flv_autostart:"D\u00E9marrage Auto",
flv_loop:"Boucle",
flv_showscalemodes:"Afficher les modes proportion",
flv_smoothvideo:"Smooth vid\u00E9o",
flv_jscallback:"JS Callback",
html5_video_options:"Options vid\u00E9o HTML5",
altsource1:"Source 1 alt\u00E9rnative",
altsource2:"Source 2 alt\u00E9rnative",
preload:"Pr\u00E9chargement",
poster:"Poster",

source:"Source"
});