// FR lang variables - Sarki pour Joomla! FR 2012-06-06
tinyMCE.addI18n('fr.style_dlg',{
title:"Ins\u00E9rer/Editer un style",
apply:"Appliquer",
toggle_insert_span:"Ins\u00E9rer une balise span",
text_tab:"Texte",
background_tab:"Fond",
block_tab:"Bloc",
box_tab:"Bo\u00EEte",
border_tab:"Bordure",
list_tab:"Liste",
positioning_tab:"Position",
text_props:"Texte",
text_font:"Police",
text_size:"Taille",
text_weight:"Largeur",
text_style:"Style",
text_variant:"Variante",
text_lineheight:"Hauteur de ligne",
text_case:"Casse",
text_color:"Couleur",
text_decoration:"D\u00E9coration",
text_overline:"Surlign\u00E9",
text_underline:"Soulign\u00E9",
text_striketrough:"Barr\u00E9",
text_blink:"Clignotant",
text_none:"Aucun",
background_color:"Couleur de fond",
background_image:"Image de fond",
background_repeat:"R\u00E9p\u00E9ter",
background_attachment:"Lier",
background_hpos:"Position horizontale",
background_vpos:"Position verticale",
block_wordspacing:"Espacement des mots",
block_letterspacing:"Espacement des lettres",
block_vertical_alignment:"Alignement vertical",
block_text_align:"Alignement du texte",
block_text_indent:"Indentation du texte",
block_whitespace:"Espaces",
block_display:"Affichage",
box_width:"Largeur",
box_height:"Hauteur",
box_float:"Position",
box_clear:"Alignement",
padding:"Marges int\u00E9rieures",
same:"Identique",
top:"Haut",
right:"Droite",
bottom:"Bas",
left:"Gauche",
margin:"Marges ext\u00E9rieures",
style:"Style",
width:"Largeur",
height:"Hauteur",
color:"Couleur",
list_type:"Type",
bullet_image:"Puces Image",
position:"Position",
positioning_type:"Type",
visibility:"Visibilit\u00E9",
zindex:"Z-index",
overflow:"Superposer",
placement:"Position",
clip:"Liaison",
text:"Texte",
background:"Fond",
block:"Bloc",
box:"Box",
border:"Bordure",
list:"Liste",
position:"Position"
});