// FR lang variables - Sarki pour Joomla! FR 2011-07-17
tinyMCE.addI18n('fr.xhtmlxtras_dlg',{
attribute_label_title:"Titre",
attribute_label_id:"ID unique",
attribute_label_class:"Classes CSS",
attribute_label_style:"Styles",
attribute_label_cite:"Citation",
attribute_label_datetime:"Date/Heure",
attribute_label_langdir:"Direction d'\u00E9criture",
attribute_option_ltr:"Gauche \u00E0 droite",
attribute_option_rtl:"Droite \u00E0 gauche",
attribute_label_langcode:"Code Langue",
attribute_label_tabindex:"Index Table",
attribute_label_accesskey:"Combinaison clavier",
attribute_events_tab:"Ev\u00E8nements",
attribute_attrib_tab:"Attributs",
general_tab:"G\u00E9n\u00E9ral",
attrib_tab:"Attributs",
events_tab:"Ev\u00E8nements",
fieldset_general_tab:"Informations",
fieldset_attrib_tab:"Attributs",
fieldset_events_tab:"Ev\u00E8nement",
title_ins_element:"Soulign\u00E9",
title_del_element:"Barr\u00E9",
title_acronym_element:"Acronyme",
title_abbr_element:"Abr\u00E9viation",
title_cite_element:"Citation",
remove:"Supprimer",
insert_date:"Ins\u00E9rer la date/heure courante",
option_ltr:"Gauche \u00E0 droite",
option_rtl:"Droite \u00E0 gauche",
attribs_title:"Ins\u00E9rer/Editer un attribut"
});