// FR lang variables - Sarki pour Joomla! FR 2011-07-17
tinyMCE.addI18n('fr.advlink_dlg',{
title:"Ins\u00E9rer/\u00E9diter un lien",
url:"Lien URL",
target:"Cible",
titlefield:"Titre",
is_email:"Cette URL semble \u00EAtre une adresse e-mail. Voule-vous ajouter le pr\u00E9fixe mailto: n\u00E9cessaire?",
is_external:"Cette URL semble \u00EAtre une adresse externe au site. Voule-vous ajouter le pr\u00E9fixe http:// n\u00E9cessaire?",
list:"Liste de liens",
general_tab:"G\u00E9n\u00E9ral",
popup_tab:"Popup",
events_tab:"Ev\u00E8nements",
advanced_tab:"Avanc\u00E9",
general_props:"Propri\u00E9t\u00E9s g\u00E9n\u00E9rales",
popup_props:"Propri\u00E9t\u00E9s du popup",
event_props:"Ev\u00E8nement",
advanced_props:"Propri\u00E9t\u00E9s avanc\u00E9es",
popup_opts:"Options",
anchor_names:"Ancre",
target_same:"Ouvrir dans cette fen\u00EAtre/cadre",
target_parent:"Ouvrir dans le cadre parent",
target_top:"Ouvrir dans le cadre principal",
target_blank:"Ouvrir dans une nouvelle fen\u00EAtre",
popup:"Activer le Popup",
popup_url:"URL du Popup",
popup_name:"Nom de la fen\u00EAtre",
popup_return:"Ins\u00E9rer un lien retour",
popup_scrollbars:"Afficher les barres de d\u00E9filement",
popup_statusbar:"Afficher la barre d'\u00E9tat",
popup_toolbar:"Afficher la barre d'outils",
popup_menubar:"Afficher la barre des menus",
popup_location:"Afficher la barre d'adresse",
popup_resizable:"Fen\u00EAtre redimensionnable",
popup_dependent:"Nouvel onglet (navigateurs r\u00E9cents)",
popup_size:"Taille",
width:"Largeur",
height:"Hauteur",
popup_position:"Position (X/Y)",
id:"Id de l'\u00E9l\u00E9ment",
style:"Styles",
classes:"Classes CSS",
target_name:"Nom de la fen\u00EAtre",
langdir:"Direction de l'\u00E9criture",
target_langcode:"Code langue de la fen\u00EAtre",
langcode:"Code langue du libell\u00E9",
encoding:"Encodage caract\u00E8res sp\u00E9ciaux",
mime:"Type MIME de la fen\u00EAtre",
rel:"Relation contenu - cible",
rev:"Relation cible - contenu",
tabindex:"Index de tabulation",
accesskey:"Combinaisons clavier",
ltr:"Gauche \u00E0 droite",
rtl:"Droite \u00E0 gauche",
link_list:"Liste de liens"
});