// FR lang variables - Sarki pour Joomla! FR 2011-07-17
tinyMCE.addI18n('fr.advimage_dlg',{
tab_general:"G\u00E9n\u00E9ral",
tab_appearance:"Apparence",
tab_advanced:"Avanc\u00E9",
general:"G\u00E9n\u00E9ral",
title:"Titre",
preview:"Pr\u00E9visualisation",
constrain_proportions:"Proportion contrainte",
langdir:"Direction de l'\u00E9criture",
langcode:"Code langue du libell\u00E9",
long_desc:"Lien vers une longue description ",
style:"Styles",
classes:"Classes CSS",
ltr:"Gauche \u00E0 droite",
rtl:"Droite \u00E0 gauche",
id:"Id de l'\u00E9l\u00E9ment",
map:"Zones cliquables (image map)",
swap_image:"Image alternative",
alt_image:"Activer",
mouseover:"Image quand le curseur est dessus",
mouseout:"Image quand le curseur est en dehors",
misc:"Attributs",
example_img:"Apparence de la prévisualisation",
missing_alt:"Etes-vous s\u00FBr de vouloir ins\u00E9rer une image sans inclure de description? Sans elle, l'image sera invisible pour les syt\u00E8mes de lecture (malvoyants, etc.), pour les navigateurs dont l'affichage des images est d\u00E9sactiv\u00E9 et, pour les moteurs de recherche!",
dialog_title:"Ins\u00E9rer/Editer une image",
src:"URL de l'image",
alt:"Description",
list:"Liste d'images",
border:"Bordure",
dimensions:"Dimensions",
width:"Largeur",
height:"Hauteur",
vspace:"Espace vertical",
hspace:"Espace horizontal",
align:"Alignement",
align_baseline:"Une ligne \u00E0 la base",
align_top:"Une ligne en haut",
align_middle:"Une ligne au milieu",
align_bottom:"Une ligne en bas",
align_texttop:"Une ligne au haut du texte",
align_textbottom:"Une ligne au bas du texte",
align_left:"Image \u00E0 gauche",
align_right:"Image \u00E0 droite",
image_list:"Liste d'images"
});