// FR lang variables - Sarki pour Joomla! FR 2011-07-17
tinyMCE.addI18n('fr.fullpage_dlg',{
title:"Propri\u00E9t\u00E9s du document",
meta_tab:"G\u00E9n\u00E9ral",
appearance_tab:"Apparence",
advanced_tab:"Avanc\u00E9",
meta_props:"M\u00E9tadonn\u00E9es",
langprops:"Encodage de langue",
meta_title:"Titre",
meta_keywords:"Mots cl\u00E9s",
meta_description:"Description",
meta_robots:"Robots",
doctypes:"Type de document",
langcode:"Code langue",
langdir:"Direction de l'\u00E9criture",
ltr:"Gauche \u00E0 droite",
rtl:"droite \u00E0 gauche",
xml_pi:"Validation XML",
encoding:"Encodage des caract\u00E8res",
appearance_bgprops:"Propri\u00E9t\u00E9s du fond",
appearance_marginprops:"Marges de la page",
appearance_linkprops:"Couleurs des liens",
appearance_textprops:"Propri\u00E9t\u00E9s du texte",
bgcolor:"Couleur de fond",
bgimage:"Image de fond",
left_margin:"Marge gauche",
right_margin:"Marge droite",
top_margin:"Marge haut",
bottom_margin:"Marge bas",
text_color:"Couleur du texte",
font_size:"Taille de police",
font_face:"Police d'\u00E9criture",
link_color:"Couleur du lien",
hover_color:"Couleur au survol",
visited_color:"Couleur apr\u00E8s visite",
active_color:"Couleur du lien actif",
textcolor:"Couleur",
fontsize:"Taille de police",
fontface:"Police d'\u00E9criture",
meta_index_follow:"Indexer et suivre le lien",
meta_index_nofollow:"Indexer mais ne pas suivre le lien",
meta_noindex_follow:"Ne pas indexer mais suivre le lien",
meta_noindex_nofollow:"Ne pas indexer et ne pas suivre le lien",
appearance_style:"Propri\u00E9t\u00E9s classes CSS et styles",
stylesheet:"Classes CSS",
style:"Styles",
author:"Auteur",
copyright:"Copyright",
add:"Ajouter un nouvel \u00E9l\u00E9ment",
remove:"Supprimer l'\u00E9l\u00E9ment s\u00E9lectionn\u00E9",
moveup:"Monter l'\u00E9l\u00E9ment s\u00E9lectionn\u00E9",
movedown:"Descendre l'\u00E9l\u00E9ment s\u00E9lectionn\u00E9",
head_elements:"En-t\u00EAtes",
info:"Information",
add_title:"Ajouter un titre",
add_meta:"Ajouter une m\u00E9tadonn\u00E9e",
add_script:"Ajouter un script",
add_style:"Ajouter un style",
add_link:"Ajouter un lien",
add_base:"Ajouter",
add_comment:"Ajouter un commentaire",
title_element:"Titre",
script_element:"Script",
style_element:"Style",
base_element:"\u00E9l\u00E9ment",
link_element:"Lien",
meta_element:"M\u00E9tadonn\u00E9e",
comment_element:"Commentaire",
src:"Source",
language:"Langue",
href:"URL",
target:"Cible",
type:"Type",
charset:"Caract\u00E8re",
defer:"Diff\u00E9rer",
media:"M\u00E9dia",
properties:"Propri\u00E9t\u00E9s",
name:"Nom",
value:"Valeur",
content:"Contenu",
rel:"Relatif",
rev:"R\u00E9vision",
hreflang:"Langue URL",
general_props:"G\u00E9n\u00E9ral",
advanced_props:"Avanc\u00E9"
});